-- Run as ADB_USER.
-- Stop before DDL or seed changes if the required source data is missing.
DECLARE
  L_COUNT PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO L_COUNT
  FROM EXT_INCIDENTS
  WHERE INCIDENT_ID = 'INC-2026-091';
  IF L_COUNT <> 1 THEN
    RAISE_APPLICATION_ERROR(-20030, 'Expected exactly one INC-2026-091');
  END IF;

  SELECT COUNT(*) INTO L_COUNT
  FROM EXT_INCIDENTS
  WHERE INCIDENT_ID = 'INC-2026-091' AND DOCUMENT_ID IS NULL;
  IF L_COUNT <> 1 THEN
    RAISE_APPLICATION_ERROR(-20031, 'Upload corrected incidents.parquet to the EXT_INCIDENTS location first');
  END IF;

  SELECT COUNT(*) INTO L_COUNT FROM EXT_INCIDENTS
  WHERE INCIDENT_ID = 'INC-2026-081'
    AND RELATED_EQUIPMENT_ID = 'EQ-NET-WA-01'
    AND DOCUMENT_ID = 'IR-2026-081';
  IF L_COUNT <> 1 THEN
    RAISE_APPLICATION_ERROR(-20032, 'Incident source does not match the demo baseline');
  END IF;

  SELECT COUNT(DISTINCT EQUIPMENT_ID) INTO L_COUNT
  FROM EXT_EQUIPMENT_MASTER
  WHERE EQUIPMENT_ID IN ('EQ-NET-WA-01', 'EQ-NET-OM-01', 'EQ-NET-NG-01');
  IF L_COUNT <> 3 THEN
    RAISE_APPLICATION_ERROR(-20033, 'Required demo equipment is missing');
  END IF;

  SELECT COUNT(DISTINCT DOCUMENT_ID) INTO L_COUNT FROM EXT_DOCUMENT_CATALOG
  WHERE DOCUMENT_ID IN ('IR-2026-081', 'SB-NW-2603', 'OPS-NET-2.1');
  IF L_COUNT <> 3 THEN
    RAISE_APPLICATION_ERROR(-20034, 'Required document catalog entries are missing');
  END IF;

  SELECT COUNT(*) INTO L_COUNT FROM USER_TABLES
  WHERE TABLE_NAME = 'LSF_IMPROVEMENT_TASKS';
  IF L_COUNT <> 1 THEN
    RAISE_APPLICATION_ERROR(-20035, 'Complete the previous article Action table setup first');
  END IF;

  DBMS_OUTPUT.PUT_LINE('Required sources: OK');
END;
/
