-- Existing tables are reused; no DROP/TRUNCATE is performed.
DECLARE
  L_COUNT PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO L_COUNT FROM USER_TABLES
  WHERE TABLE_NAME = 'LSF_KG_LOT_PATCH';
  IF L_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE LSF_KG_LOT_PATCH (
  EQUIPMENT_ID       VARCHAR2(40)  PRIMARY KEY,
  MANUFACTURING_LOT  VARCHAR2(40)  NOT NULL,
  SOURCE_TYPE        VARCHAR2(30)  DEFAULT 'SYNTHETIC_DEMO' NOT NULL,
  SOURCE_REFERENCE_ID VARCHAR2(40) NOT NULL,
  ASSERTION_STATUS   VARCHAR2(20)  DEFAULT 'SYNTHETIC' NOT NULL,
  EFFECTIVE_DATE     DATE          NOT NULL,
  NOTE               VARCHAR2(500),
  CONSTRAINT CK_LSF_KG_LOT_PATCH_STATUS
    CHECK (ASSERTION_STATUS IN ('VERIFIED', 'PROVISIONAL', 'SYNTHETIC'))
)~';
    DBMS_OUTPUT.PUT_LINE('Created LSF_KG_LOT_PATCH');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Reusing LSF_KG_LOT_PATCH');
  END IF;
END;
/

DECLARE
  L_COUNT PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO L_COUNT FROM USER_TABLES
  WHERE TABLE_NAME = 'LSF_KG_TASK_EQUIPMENT';
  IF L_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE LSF_KG_TASK_EQUIPMENT (
  TASK_ID       NUMBER       NOT NULL,
  EQUIPMENT_ID  VARCHAR2(40) NOT NULL,
  SOURCE_TYPE   VARCHAR2(30) DEFAULT 'SYNTHETIC_DEMO' NOT NULL,
  SOURCE_REFERENCE_ID VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_LSF_KG_TASK_EQUIPMENT
    PRIMARY KEY (TASK_ID, EQUIPMENT_ID)
)~';
    DBMS_OUTPUT.PUT_LINE('Created LSF_KG_TASK_EQUIPMENT');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Reusing LSF_KG_TASK_EQUIPMENT');
  END IF;
END;
/

DECLARE
  L_COUNT PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO L_COUNT FROM USER_TABLES
  WHERE TABLE_NAME = 'LSF_KG_TASK_DOCUMENT';
  IF L_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE LSF_KG_TASK_DOCUMENT (
  TASK_ID      NUMBER       NOT NULL,
  DOCUMENT_ID  VARCHAR2(40) NOT NULL,
  SOURCE_TYPE  VARCHAR2(30) DEFAULT 'SYNTHETIC_DEMO' NOT NULL,
  SOURCE_REFERENCE_ID VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_LSF_KG_TASK_DOCUMENT
    PRIMARY KEY (TASK_ID, DOCUMENT_ID)
)~';
    DBMS_OUTPUT.PUT_LINE('Created LSF_KG_TASK_DOCUMENT');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Reusing LSF_KG_TASK_DOCUMENT');
  END IF;
END;
/

DECLARE
  L_COUNT PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO L_COUNT FROM USER_TABLES
  WHERE TABLE_NAME = 'LSF_KG_LOT_DOCUMENT';
  IF L_COUNT = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE LSF_KG_LOT_DOCUMENT (
  MANUFACTURING_LOT VARCHAR2(40) NOT NULL,
  DOCUMENT_ID       VARCHAR2(40) NOT NULL,
  RELATION_TYPE     VARCHAR2(40) DEFAULT 'APPLICABLE_GUIDANCE' NOT NULL,
  SOURCE_TYPE       VARCHAR2(30) DEFAULT 'SYNTHETIC_DEMO' NOT NULL,
  SOURCE_REFERENCE_ID VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_LSF_KG_LOT_DOCUMENT
    PRIMARY KEY (MANUFACTURING_LOT, DOCUMENT_ID)
)~';
    DBMS_OUTPUT.PUT_LINE('Created LSF_KG_LOT_DOCUMENT');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Reusing LSF_KG_LOT_DOCUMENT');
  END IF;
END;
/
