-- Run as ADB_USER.
-- Re-running resets only the two ONTOLOGY_DEMO_SEED tasks to OPEN.
MERGE INTO LSF_KG_LOT_PATCH T
USING (
  SELECT
    'EQ-NET-OM-01' AS EQUIPMENT_ID,
    'NW-2603'      AS MANUFACTURING_LOT,
    'SYNTHETIC_DEMO' AS SOURCE_TYPE,
    'BLOG-DEMO-LOT-001' AS SOURCE_REFERENCE_ID,
    'SYNTHETIC'    AS ASSERTION_STATUS,
    DATE '2026-07-12' AS EFFECTIVE_DATE,
    'Knowledge Graph検証用の合成Lot Relation' AS NOTE
  FROM DUAL
  UNION ALL
  SELECT
    'EQ-NET-NG-01',
    'NW-2603',
    'SYNTHETIC_DEMO',
    'BLOG-DEMO-LOT-001',
    'SYNTHETIC',
    DATE '2026-07-12',
    'Knowledge Graph検証用の合成Lot Relation'
  FROM DUAL
) S
ON (T.EQUIPMENT_ID = S.EQUIPMENT_ID)
WHEN MATCHED THEN
  UPDATE SET
    T.MANUFACTURING_LOT = S.MANUFACTURING_LOT,
    T.SOURCE_TYPE = S.SOURCE_TYPE,
    T.SOURCE_REFERENCE_ID = S.SOURCE_REFERENCE_ID,
    T.ASSERTION_STATUS = S.ASSERTION_STATUS,
    T.EFFECTIVE_DATE = S.EFFECTIVE_DATE,
    T.NOTE = S.NOTE
WHEN NOT MATCHED THEN
  INSERT (
    EQUIPMENT_ID, MANUFACTURING_LOT, SOURCE_TYPE, SOURCE_REFERENCE_ID,
    ASSERTION_STATUS, EFFECTIVE_DATE, NOTE
  )
  VALUES (
    S.EQUIPMENT_ID, S.MANUFACTURING_LOT, S.SOURCE_TYPE,
    S.SOURCE_REFERENCE_ID,
    S.ASSERTION_STATUS, S.EFFECTIVE_DATE, S.NOTE
  );

DECLARE
  L_TASK_OM_ID NUMBER;
  L_TASK_NG_ID NUMBER;

  PROCEDURE UPSERT_DEMO_TASK (
    P_TASK_TITLE       IN  VARCHAR2,
    P_TASK_DESCRIPTION IN  VARCHAR2,
    P_PRIORITY         IN  VARCHAR2,
    P_TASK_ID          OUT NUMBER
  ) AS
    L_COUNT PLS_INTEGER;
  BEGIN
    SELECT COUNT(*), MIN(TASK_ID)
      INTO L_COUNT, P_TASK_ID
      FROM LSF_IMPROVEMENT_TASKS
     WHERE INCIDENT_ID = 'INC-2026-081'
       AND TASK_TITLE = P_TASK_TITLE
       AND CREATED_BY_AGENT = 'ONTOLOGY_DEMO_SEED';

    IF L_COUNT > 1 THEN
      RAISE_APPLICATION_ERROR(-20021, 'Duplicate ontology demo task');
    ELSIF L_COUNT = 0 THEN
      INSERT INTO LSF_IMPROVEMENT_TASKS (
        INCIDENT_ID, TASK_TITLE, TASK_DESCRIPTION,
        PRIORITY, OWNER_TEAM_ID, CREATED_BY_AGENT, STATUS
      ) VALUES (
        'INC-2026-081', P_TASK_TITLE, P_TASK_DESCRIPTION,
        P_PRIORITY, 'TEAM-NOC', 'ONTOLOGY_DEMO_SEED', 'OPEN'
      )
      RETURNING TASK_ID INTO P_TASK_ID;
    ELSE
      UPDATE LSF_IMPROVEMENT_TASKS
         SET TASK_DESCRIPTION = P_TASK_DESCRIPTION,
             PRIORITY = P_PRIORITY,
             OWNER_TEAM_ID = 'TEAM-NOC',
             STATUS = 'OPEN'
       WHERE TASK_ID = P_TASK_ID;
    END IF;
  END UPSERT_DEMO_TASK;
BEGIN
  UPSERT_DEMO_TASK(
    P_TASK_TITLE       => 'Orbit Main StageのNW-2603予防交換',
    P_TASK_DESCRIPTION => 'EQ-NET-OM-01を開演前に隔離し、冷却ファン・制御基板を交換する。',
    P_PRIORITY         => 'CRITICAL',
    P_TASK_ID          => L_TASK_OM_ID
  );

  UPSERT_DEMO_TASK(
    P_TASK_TITLE       => 'Neon Groove StageのNW-2603予防交換',
    P_TASK_DESCRIPTION => 'EQ-NET-NG-01を開演前に隔離し、冷却ファン・制御基板を交換する。',
    P_PRIORITY         => 'HIGH',
    P_TASK_ID          => L_TASK_NG_ID
  );

  MERGE INTO LSF_KG_TASK_EQUIPMENT T
  USING (
    SELECT L_TASK_OM_ID AS TASK_ID,
           'EQ-NET-OM-01' AS EQUIPMENT_ID FROM DUAL
    UNION ALL
    SELECT L_TASK_NG_ID, 'EQ-NET-NG-01' FROM DUAL
  ) S
  ON (T.TASK_ID = S.TASK_ID AND T.EQUIPMENT_ID = S.EQUIPMENT_ID)
  WHEN MATCHED THEN
    UPDATE SET
      T.SOURCE_TYPE = 'SYNTHETIC_DEMO',
      T.SOURCE_REFERENCE_ID = 'BLOG-DEMO-TASK-001'
  WHEN NOT MATCHED THEN
    INSERT (
      TASK_ID, EQUIPMENT_ID, SOURCE_TYPE, SOURCE_REFERENCE_ID
    ) VALUES (
      S.TASK_ID, S.EQUIPMENT_ID,
      'SYNTHETIC_DEMO', 'BLOG-DEMO-TASK-001'
    );

  MERGE INTO LSF_KG_TASK_DOCUMENT T
  USING (
    SELECT L_TASK_OM_ID AS TASK_ID,
           'SB-NW-2603' AS DOCUMENT_ID FROM DUAL
    UNION ALL
    SELECT L_TASK_OM_ID, 'OPS-NET-2.1' FROM DUAL
    UNION ALL
    SELECT L_TASK_NG_ID, 'SB-NW-2603' FROM DUAL
    UNION ALL
    SELECT L_TASK_NG_ID, 'OPS-NET-2.1' FROM DUAL
  ) S
  ON (T.TASK_ID = S.TASK_ID AND T.DOCUMENT_ID = S.DOCUMENT_ID)
  WHEN MATCHED THEN
    UPDATE SET
      T.SOURCE_TYPE = 'SYNTHETIC_DEMO',
      T.SOURCE_REFERENCE_ID = 'BLOG-DEMO-TASK-001'
  WHEN NOT MATCHED THEN
    INSERT (
      TASK_ID, DOCUMENT_ID, SOURCE_TYPE, SOURCE_REFERENCE_ID
    ) VALUES (
      S.TASK_ID, S.DOCUMENT_ID,
      'SYNTHETIC_DEMO', 'BLOG-DEMO-TASK-001'
    );

  MERGE INTO LSF_KG_LOT_DOCUMENT T
  USING (
    SELECT
      'NW-2603' AS MANUFACTURING_LOT,
      'SB-NW-2603' AS DOCUMENT_ID,
      'SERVICE_BULLETIN' AS RELATION_TYPE
    FROM DUAL
    UNION ALL
    SELECT 'NW-2603', 'OPS-NET-2.1', 'OPERATING_PROCEDURE'
    FROM DUAL
  ) S
  ON (
    T.MANUFACTURING_LOT = S.MANUFACTURING_LOT
    AND T.DOCUMENT_ID = S.DOCUMENT_ID
  )
  WHEN MATCHED THEN
    UPDATE SET
      T.RELATION_TYPE = S.RELATION_TYPE,
      T.SOURCE_TYPE = 'SYNTHETIC_DEMO',
      T.SOURCE_REFERENCE_ID = 'BLOG-DEMO-DOC-001'
  WHEN NOT MATCHED THEN
    INSERT (
      MANUFACTURING_LOT, DOCUMENT_ID, RELATION_TYPE,
      SOURCE_TYPE, SOURCE_REFERENCE_ID
    ) VALUES (
      S.MANUFACTURING_LOT, S.DOCUMENT_ID, S.RELATION_TYPE,
      'SYNTHETIC_DEMO', 'BLOG-DEMO-DOC-001'
    );

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
