CREATE OR REPLACE VIEW V_KG_LOCATION_SCOPE AS
SELECT CAST(STAGE_ID AS VARCHAR2(40)) AS LOCATION_ID,
       CAST('IN_SCOPE' AS VARCHAR2(20)) AS SCOPE_STATUS
FROM EXT_STAGES
UNION ALL
SELECT X.LOCATION_ID,
       CAST('OUT_OF_SCOPE' AS VARCHAR2(20))
FROM (
  SELECT DISTINCT CAST(G.GATE_ID AS VARCHAR2(40)) AS LOCATION_ID
  FROM V_GATE_CONGESTION_ANALYSIS G
  WHERE G.GATE_ID IS NOT NULL
  UNION
  SELECT CAST('GATE-S' AS VARCHAR2(40)) FROM DUAL
  UNION
  SELECT CAST('MERCH-CENTRAL' AS VARCHAR2(40)) FROM DUAL
  UNION
  SELECT CAST('MERCH-NORTH' AS VARCHAR2(40)) FROM DUAL
) X
WHERE X.LOCATION_ID IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM EXT_STAGES S WHERE S.STAGE_ID = X.LOCATION_ID
  );

CREATE OR REPLACE VIEW V_KG_SOURCE_SCOPE_AUDIT AS
SELECT 'INCIDENT' AS ENTITY_TYPE,
       CAST(I.INCIDENT_ID AS VARCHAR2(40)) AS ENTITY_ID,
       CAST(I.LOCATION_ID AS VARCHAR2(40)) AS LOCATION_ID,
       COALESCE(S.SCOPE_STATUS, 'UNKNOWN_OR_MISSING') AS SCOPE_STATUS
FROM EXT_INCIDENTS I
LEFT JOIN V_KG_LOCATION_SCOPE S ON S.LOCATION_ID = I.LOCATION_ID
UNION ALL
SELECT 'EQUIPMENT', CAST(E.EQUIPMENT_ID AS VARCHAR2(40)),
       CAST(E.STAGE_ID AS VARCHAR2(40)),
       COALESCE(S.SCOPE_STATUS, 'UNKNOWN_OR_MISSING')
FROM EXT_EQUIPMENT_MASTER E
LEFT JOIN V_KG_LOCATION_SCOPE S ON S.LOCATION_ID = E.STAGE_ID
UNION ALL
SELECT 'TASK', CAST(TO_CHAR(T.TASK_ID) AS VARCHAR2(40)),
       CAST(I.LOCATION_ID AS VARCHAR2(40)),
       CASE WHEN I.INCIDENT_ID IS NULL THEN 'UNKNOWN_OR_MISSING'
            ELSE COALESCE(S.SCOPE_STATUS, 'UNKNOWN_OR_MISSING') END
FROM LSF_IMPROVEMENT_TASKS T
LEFT JOIN EXT_INCIDENTS I ON I.INCIDENT_ID = T.INCIDENT_ID
LEFT JOIN V_KG_LOCATION_SCOPE S ON S.LOCATION_ID = I.LOCATION_ID;

SELECT ENTITY_TYPE, ENTITY_ID, LOCATION_ID, SCOPE_STATUS
FROM V_KG_SOURCE_SCOPE_AUDIT
WHERE SCOPE_STATUS <> 'IN_SCOPE'
ORDER BY SCOPE_STATUS, ENTITY_TYPE, ENTITY_ID;
