-- Run as ADB_USER.
-- Data preparation checks. Full graph source/edge checks remain in the blog.
DECLARE
  L_COUNT PLS_INTEGER;
  PROCEDURE CHECK_COUNT(P_LABEL VARCHAR2, P_ACTUAL NUMBER, P_EXPECTED NUMBER) AS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(P_LABEL || ': ' || P_ACTUAL || ' (expected ' || P_EXPECTED || ')');
    IF P_ACTUAL <> P_EXPECTED THEN
      RAISE_APPLICATION_ERROR(-20040, P_LABEL || ' count mismatch');
    END IF;
  END;
BEGIN
  SELECT COUNT(*) INTO L_COUNT
  FROM V_KG_SOURCE_SCOPE_AUDIT WHERE SCOPE_STATUS = 'UNKNOWN_OR_MISSING';
  CHECK_COUNT('SCOPE_UNKNOWN_OR_MISSING', L_COUNT, 0);

  SELECT COUNT(*) INTO L_COUNT
  FROM EXT_EQUIPMENT_MASTER E
  LEFT JOIN V_KG_LOCATION_SCOPE S ON S.LOCATION_ID = E.STAGE_ID
  WHERE S.LOCATION_ID IS NULL;
  CHECK_COUNT('EQUIPMENT_STAGE_SOURCE', L_COUNT, 0);

  SELECT COUNT(*) INTO L_COUNT
  FROM EXT_INCIDENTS I JOIN EXT_STAGES S ON S.STAGE_ID = I.LOCATION_ID
  LEFT JOIN EXT_DOCUMENT_CATALOG D ON D.DOCUMENT_ID = I.DOCUMENT_ID
  WHERE I.DOCUMENT_ID IS NOT NULL AND D.DOCUMENT_ID IS NULL;
  CHECK_COUNT('INCIDENT_DOCUMENT_SOURCE', L_COUNT, 0);

  SELECT COUNT(*) INTO L_COUNT FROM LSF_KG_LOT_PATCH
  WHERE EQUIPMENT_ID IN ('EQ-NET-OM-01', 'EQ-NET-NG-01')
    AND MANUFACTURING_LOT = 'NW-2603' AND ASSERTION_STATUS = 'SYNTHETIC'
    AND SOURCE_TYPE = 'SYNTHETIC_DEMO' AND SOURCE_REFERENCE_ID = 'BLOG-DEMO-LOT-001';
  CHECK_COUNT('DEMO_LOT_PATCH', L_COUNT, 2);

  SELECT COUNT(*) INTO L_COUNT FROM LSF_IMPROVEMENT_TASKS
  WHERE INCIDENT_ID = 'INC-2026-081' AND CREATED_BY_AGENT = 'ONTOLOGY_DEMO_SEED'
    AND TASK_TITLE IN ('Orbit Main StageのNW-2603予防交換', 'Neon Groove StageのNW-2603予防交換')
    AND STATUS = 'OPEN';
  CHECK_COUNT('DEMO_OPEN_TASKS', L_COUNT, 2);

  SELECT COUNT(*) INTO L_COUNT
  FROM LSF_KG_TASK_EQUIPMENT M JOIN LSF_IMPROVEMENT_TASKS T ON T.TASK_ID = M.TASK_ID
  WHERE T.INCIDENT_ID = 'INC-2026-081' AND T.CREATED_BY_AGENT = 'ONTOLOGY_DEMO_SEED'
    AND M.SOURCE_REFERENCE_ID = 'BLOG-DEMO-TASK-001'
    AND ((T.TASK_TITLE = 'Orbit Main StageのNW-2603予防交換' AND M.EQUIPMENT_ID = 'EQ-NET-OM-01')
      OR (T.TASK_TITLE = 'Neon Groove StageのNW-2603予防交換' AND M.EQUIPMENT_ID = 'EQ-NET-NG-01'));
  CHECK_COUNT('DEMO_TASK_EQUIPMENT', L_COUNT, 2);

  SELECT COUNT(*) INTO L_COUNT
  FROM LSF_KG_TASK_DOCUMENT M JOIN LSF_IMPROVEMENT_TASKS T ON T.TASK_ID = M.TASK_ID
  WHERE T.INCIDENT_ID = 'INC-2026-081' AND T.CREATED_BY_AGENT = 'ONTOLOGY_DEMO_SEED'
    AND T.TASK_TITLE IN ('Orbit Main StageのNW-2603予防交換', 'Neon Groove StageのNW-2603予防交換')
    AND M.DOCUMENT_ID IN ('SB-NW-2603', 'OPS-NET-2.1')
    AND M.SOURCE_REFERENCE_ID = 'BLOG-DEMO-TASK-001';
  CHECK_COUNT('DEMO_TASK_DOCUMENT', L_COUNT, 4);

  SELECT COUNT(*) INTO L_COUNT FROM LSF_KG_LOT_DOCUMENT
  WHERE MANUFACTURING_LOT = 'NW-2603'
    AND DOCUMENT_ID IN ('SB-NW-2603', 'OPS-NET-2.1')
    AND SOURCE_REFERENCE_ID = 'BLOG-DEMO-DOC-001';
  CHECK_COUNT('DEMO_LOT_DOCUMENT', L_COUNT, 2);
END;
/

SELECT INCIDENT_ID, DOCUMENT_ID FROM EXT_INCIDENTS
WHERE INCIDENT_ID = 'INC-2026-091';

SELECT TASK_ID, TASK_TITLE, STATUS FROM LSF_IMPROVEMENT_TASKS
WHERE INCIDENT_ID = 'INC-2026-081' AND CREATED_BY_AGENT = 'ONTOLOGY_DEMO_SEED'
  AND TASK_TITLE IN ('Orbit Main StageのNW-2603予防交換', 'Neon Groove StageのNW-2603予防交換')
ORDER BY TASK_ID;
