-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 1152-1250; console output omitted.

CREATE OR REPLACE VIEW V_KG_INCIDENTS AS
SELECT
  CAST(I.INCIDENT_ID AS VARCHAR2(40)) AS INCIDENT_ID,
  I.FESTIVAL_DATE,
  CAST(I.LOCATION_ID AS VARCHAR2(40)) AS LOCATION_ID,
  I.CATEGORY,
  I.SEVERITY,
  I.START_TS,
  I.END_TS,
  I.TITLE,
  I.IMPACTED_PEOPLE,
  CAST(I.RELATED_EQUIPMENT_ID AS VARCHAR2(40))
    AS RELATED_EQUIPMENT_ID,
  CAST(I.STATUS AS VARCHAR2(40)) AS STATUS,
  CAST(I.DOCUMENT_ID AS VARCHAR2(40)) AS DOCUMENT_ID,
  I.SUMMARY
FROM EXT_INCIDENTS I
JOIN EXT_STAGES S
  ON S.STAGE_ID = I.LOCATION_ID;

CREATE OR REPLACE VIEW V_KG_EQUIPMENT AS
SELECT
  CAST(E.EQUIPMENT_ID AS VARCHAR2(40)) AS EQUIPMENT_ID,
  CAST(E.STAGE_ID AS VARCHAR2(40)) AS STAGE_ID,
  E.EQUIPMENT_CATEGORY,
  E.MODEL_NAME,
  E.SERIAL_NUMBER,
  CAST(
    COALESCE(P.MANUFACTURING_LOT, E.MANUFACTURING_LOT)
    AS VARCHAR2(40)
  ) AS MANUFACTURING_LOT,
  E.VENDOR_ID,
  E.FIRMWARE_VERSION,
  E.INSTALLED_DATE,
  E.CRITICALITY,
  CASE
    WHEN P.EQUIPMENT_ID IS NOT NULL THEN P.SOURCE_TYPE
    ELSE 'MASTER_CSV'
  END AS LOT_SOURCE,
  CASE
    WHEN P.EQUIPMENT_ID IS NOT NULL THEN P.ASSERTION_STATUS
    ELSE 'SOURCE_RECORD'
  END AS LOT_ASSERTION_STATUS,
  CAST(
    CASE WHEN P.EQUIPMENT_ID IS NOT NULL THEN P.SOURCE_REFERENCE_ID
         ELSE 'equipment_master.csv#' || E.EQUIPMENT_ID END
    AS VARCHAR2(200)
  ) AS LOT_SOURCE_REFERENCE_ID
FROM EXT_EQUIPMENT_MASTER E
JOIN EXT_STAGES S
  ON S.STAGE_ID = E.STAGE_ID
LEFT JOIN LSF_KG_LOT_PATCH P
  ON P.EQUIPMENT_ID = E.EQUIPMENT_ID
 AND P.ASSERTION_STATUS = 'SYNTHETIC';

CREATE OR REPLACE VIEW V_KG_STAGES AS
SELECT
  CAST(STAGE_ID AS VARCHAR2(40)) AS STAGE_ID,
  STAGE_NAME,
  STAGE_TYPE,
  CAPACITY,
  LOCATION_ZONE,
  NETWORK_ZONE,
  WEATHER_EXPOSED_FLAG
FROM EXT_STAGES;

CREATE OR REPLACE VIEW V_KG_LOTS AS
SELECT DISTINCT
  MANUFACTURING_LOT
FROM V_KG_EQUIPMENT
WHERE MANUFACTURING_LOT IS NOT NULL;

CREATE OR REPLACE VIEW V_KG_TASKS AS
SELECT
  T.TASK_ID,
  'TASK-' || TO_CHAR(T.TASK_ID) AS TASK_CODE,
  CAST(T.INCIDENT_ID AS VARCHAR2(40)) AS INCIDENT_ID,
  T.TASK_TITLE,
  T.TASK_DESCRIPTION,
  T.PRIORITY,
  T.OWNER_TEAM_ID,
  T.CREATED_BY_AGENT,
  T.CREATED_AT,
  CAST(T.STATUS AS VARCHAR2(40)) AS STATUS
FROM LSF_IMPROVEMENT_TASKS T
JOIN V_KG_INCIDENTS I
  ON I.INCIDENT_ID = T.INCIDENT_ID;

CREATE OR REPLACE VIEW V_KG_DOCUMENTS AS
SELECT
  CAST(DOCUMENT_ID AS VARCHAR2(40)) AS DOCUMENT_ID,
  FILE_NAME,
  DOCUMENT_TYPE,
  VERSION,
  EFFECTIVE_DATE,
  PURPOSE
FROM EXT_DOCUMENT_CATALOG;
