-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 1260-1347; console output omitted.

CREATE OR REPLACE VIEW V_KG_INCIDENT_AFFECTS AS
SELECT
  I.INCIDENT_ID || '|AFFECTS|' || I.RELATED_EQUIPMENT_ID AS EDGE_ID,
  I.INCIDENT_ID,
  I.RELATED_EQUIPMENT_ID AS EQUIPMENT_ID
FROM V_KG_INCIDENTS I
JOIN V_KG_EQUIPMENT E
  ON E.EQUIPMENT_ID = I.RELATED_EQUIPMENT_ID;

CREATE OR REPLACE VIEW V_KG_EQUIPMENT_LOT AS
SELECT
  E.EQUIPMENT_ID || '|LOT|' || E.MANUFACTURING_LOT AS EDGE_ID,
  E.EQUIPMENT_ID,
  E.MANUFACTURING_LOT,
  E.LOT_SOURCE,
  E.LOT_ASSERTION_STATUS,
  E.LOT_SOURCE_REFERENCE_ID
FROM V_KG_EQUIPMENT E
WHERE E.MANUFACTURING_LOT IS NOT NULL;

CREATE OR REPLACE VIEW V_KG_EQUIPMENT_STAGE AS
SELECT
  E.EQUIPMENT_ID || '|STAGE|' || E.STAGE_ID AS EDGE_ID,
  E.EQUIPMENT_ID,
  E.STAGE_ID
FROM V_KG_EQUIPMENT E
JOIN V_KG_STAGES S
  ON S.STAGE_ID = E.STAGE_ID;

CREATE OR REPLACE VIEW V_KG_INCIDENT_DOCUMENT AS
SELECT
  I.INCIDENT_ID || '|DOC|' || I.DOCUMENT_ID AS EDGE_ID,
  I.INCIDENT_ID,
  I.DOCUMENT_ID
FROM V_KG_INCIDENTS I
JOIN V_KG_DOCUMENTS D
  ON D.DOCUMENT_ID = I.DOCUMENT_ID;

CREATE OR REPLACE VIEW V_KG_INCIDENT_TASK AS
SELECT
  T.INCIDENT_ID || '|TASK|' || TO_CHAR(T.TASK_ID) AS EDGE_ID,
  T.INCIDENT_ID,
  T.TASK_ID
FROM V_KG_TASKS T
JOIN V_KG_INCIDENTS I
  ON I.INCIDENT_ID = T.INCIDENT_ID;

CREATE OR REPLACE VIEW V_KG_TASK_EQUIPMENT AS
SELECT
  TO_CHAR(M.TASK_ID) || '|TARGETS|' || M.EQUIPMENT_ID AS EDGE_ID,
  M.TASK_ID,
  M.EQUIPMENT_ID,
  M.SOURCE_TYPE,
  M.SOURCE_REFERENCE_ID
FROM LSF_KG_TASK_EQUIPMENT M
JOIN V_KG_TASKS T
  ON T.TASK_ID = M.TASK_ID
JOIN V_KG_EQUIPMENT E
  ON E.EQUIPMENT_ID = M.EQUIPMENT_ID;

CREATE OR REPLACE VIEW V_KG_TASK_DOCUMENT AS
SELECT
  TO_CHAR(M.TASK_ID) || '|USES|' || M.DOCUMENT_ID AS EDGE_ID,
  M.TASK_ID,
  M.DOCUMENT_ID,
  M.SOURCE_TYPE,
  M.SOURCE_REFERENCE_ID
FROM LSF_KG_TASK_DOCUMENT M
JOIN V_KG_TASKS T
  ON T.TASK_ID = M.TASK_ID
JOIN V_KG_DOCUMENTS D
  ON D.DOCUMENT_ID = M.DOCUMENT_ID;

CREATE OR REPLACE VIEW V_KG_LOT_DOCUMENT AS
SELECT
  M.MANUFACTURING_LOT || '|DOC|' || M.DOCUMENT_ID AS EDGE_ID,
  M.MANUFACTURING_LOT,
  M.DOCUMENT_ID,
  M.RELATION_TYPE,
  M.SOURCE_TYPE,
  M.SOURCE_REFERENCE_ID
FROM LSF_KG_LOT_DOCUMENT M
JOIN V_KG_LOTS L
  ON L.MANUFACTURING_LOT = M.MANUFACTURING_LOT
JOIN V_KG_DOCUMENTS D
  ON D.DOCUMENT_ID = M.DOCUMENT_ID;
