-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 1383-1465, blog v1.3 lines 1473-1529, blog v1.3 lines 1665-1732; console output omitted.

WITH KEY_ERRORS (ELEMENT_KIND, ELEMENT_NAME, ERROR_COUNT) AS (
  SELECT 'VERTEX', 'INCIDENTS', COUNT(*) FROM (
    SELECT INCIDENT_ID FROM V_KG_INCIDENTS
    GROUP BY INCIDENT_ID
    HAVING INCIDENT_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'VERTEX', 'EQUIPMENTS', COUNT(*) FROM (
    SELECT EQUIPMENT_ID FROM V_KG_EQUIPMENT
    GROUP BY EQUIPMENT_ID
    HAVING EQUIPMENT_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'VERTEX', 'STAGES', COUNT(*) FROM (
    SELECT STAGE_ID FROM V_KG_STAGES
    GROUP BY STAGE_ID
    HAVING STAGE_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'VERTEX', 'LOTS', COUNT(*) FROM (
    SELECT MANUFACTURING_LOT FROM V_KG_LOTS
    GROUP BY MANUFACTURING_LOT
    HAVING MANUFACTURING_LOT IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'VERTEX', 'TASKS', COUNT(*) FROM (
    SELECT TASK_ID FROM V_KG_TASKS
    GROUP BY TASK_ID
    HAVING TASK_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'VERTEX', 'DOCUMENTS', COUNT(*) FROM (
    SELECT DOCUMENT_ID FROM V_KG_DOCUMENTS
    GROUP BY DOCUMENT_ID
    HAVING DOCUMENT_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'EDGE', 'INCIDENT_AFFECTS', COUNT(*) FROM (
    SELECT EDGE_ID FROM V_KG_INCIDENT_AFFECTS
    GROUP BY EDGE_ID HAVING EDGE_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'EDGE', 'EQUIPMENT_LOT', COUNT(*) FROM (
    SELECT EDGE_ID FROM V_KG_EQUIPMENT_LOT
    GROUP BY EDGE_ID HAVING EDGE_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'EDGE', 'EQUIPMENT_STAGE', COUNT(*) FROM (
    SELECT EDGE_ID FROM V_KG_EQUIPMENT_STAGE
    GROUP BY EDGE_ID HAVING EDGE_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'EDGE', 'INCIDENT_DOCUMENT', COUNT(*) FROM (
    SELECT EDGE_ID FROM V_KG_INCIDENT_DOCUMENT
    GROUP BY EDGE_ID HAVING EDGE_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'EDGE', 'INCIDENT_TASK', COUNT(*) FROM (
    SELECT EDGE_ID FROM V_KG_INCIDENT_TASK
    GROUP BY EDGE_ID HAVING EDGE_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'EDGE', 'TASK_EQUIPMENT', COUNT(*) FROM (
    SELECT EDGE_ID FROM V_KG_TASK_EQUIPMENT
    GROUP BY EDGE_ID HAVING EDGE_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'EDGE', 'TASK_DOCUMENT', COUNT(*) FROM (
    SELECT EDGE_ID FROM V_KG_TASK_DOCUMENT
    GROUP BY EDGE_ID HAVING EDGE_ID IS NULL OR COUNT(*) > 1
  )
  UNION ALL
  SELECT 'EDGE', 'LOT_DOCUMENT', COUNT(*) FROM (
    SELECT EDGE_ID FROM V_KG_LOT_DOCUMENT
    GROUP BY EDGE_ID HAVING EDGE_ID IS NULL OR COUNT(*) > 1
  )
)
SELECT ELEMENT_KIND, ELEMENT_NAME, ERROR_COUNT
FROM KEY_ERRORS
WHERE ERROR_COUNT > 0
ORDER BY ELEMENT_KIND, ELEMENT_NAME;

WITH ENDPOINT_ERRORS (EDGE_NAME, ERROR_COUNT) AS (
  SELECT 'INCIDENT_AFFECTS', COUNT(*)
  FROM V_KG_INCIDENT_AFFECTS E
  LEFT JOIN V_KG_INCIDENTS S ON S.INCIDENT_ID = E.INCIDENT_ID
  LEFT JOIN V_KG_EQUIPMENT D ON D.EQUIPMENT_ID = E.EQUIPMENT_ID
  WHERE S.INCIDENT_ID IS NULL OR D.EQUIPMENT_ID IS NULL
  UNION ALL
  SELECT 'EQUIPMENT_LOT', COUNT(*)
  FROM V_KG_EQUIPMENT_LOT E
  LEFT JOIN V_KG_EQUIPMENT S ON S.EQUIPMENT_ID = E.EQUIPMENT_ID
  LEFT JOIN V_KG_LOTS D
    ON D.MANUFACTURING_LOT = E.MANUFACTURING_LOT
  WHERE S.EQUIPMENT_ID IS NULL OR D.MANUFACTURING_LOT IS NULL
  UNION ALL
  SELECT 'EQUIPMENT_STAGE', COUNT(*)
  FROM V_KG_EQUIPMENT_STAGE E
  LEFT JOIN V_KG_EQUIPMENT S ON S.EQUIPMENT_ID = E.EQUIPMENT_ID
  LEFT JOIN V_KG_STAGES D ON D.STAGE_ID = E.STAGE_ID
  WHERE S.EQUIPMENT_ID IS NULL OR D.STAGE_ID IS NULL
  UNION ALL
  SELECT 'INCIDENT_DOCUMENT', COUNT(*)
  FROM V_KG_INCIDENT_DOCUMENT E
  LEFT JOIN V_KG_INCIDENTS S ON S.INCIDENT_ID = E.INCIDENT_ID
  LEFT JOIN V_KG_DOCUMENTS D ON D.DOCUMENT_ID = E.DOCUMENT_ID
  WHERE S.INCIDENT_ID IS NULL OR D.DOCUMENT_ID IS NULL
  UNION ALL
  SELECT 'INCIDENT_TASK', COUNT(*)
  FROM V_KG_INCIDENT_TASK E
  LEFT JOIN V_KG_INCIDENTS S ON S.INCIDENT_ID = E.INCIDENT_ID
  LEFT JOIN V_KG_TASKS D ON D.TASK_ID = E.TASK_ID
  WHERE S.INCIDENT_ID IS NULL OR D.TASK_ID IS NULL
  UNION ALL
  SELECT 'TASK_EQUIPMENT', COUNT(*)
  FROM V_KG_TASK_EQUIPMENT E
  LEFT JOIN V_KG_TASKS S ON S.TASK_ID = E.TASK_ID
  LEFT JOIN V_KG_EQUIPMENT D ON D.EQUIPMENT_ID = E.EQUIPMENT_ID
  WHERE S.TASK_ID IS NULL OR D.EQUIPMENT_ID IS NULL
  UNION ALL
  SELECT 'TASK_DOCUMENT', COUNT(*)
  FROM V_KG_TASK_DOCUMENT E
  LEFT JOIN V_KG_TASKS S ON S.TASK_ID = E.TASK_ID
  LEFT JOIN V_KG_DOCUMENTS D ON D.DOCUMENT_ID = E.DOCUMENT_ID
  WHERE S.TASK_ID IS NULL OR D.DOCUMENT_ID IS NULL
  UNION ALL
  SELECT 'LOT_DOCUMENT', COUNT(*)
  FROM V_KG_LOT_DOCUMENT E
  LEFT JOIN V_KG_LOTS S
    ON S.MANUFACTURING_LOT = E.MANUFACTURING_LOT
  LEFT JOIN V_KG_DOCUMENTS D ON D.DOCUMENT_ID = E.DOCUMENT_ID
  WHERE S.MANUFACTURING_LOT IS NULL OR D.DOCUMENT_ID IS NULL
)
SELECT EDGE_NAME, ERROR_COUNT
FROM ENDPOINT_ERRORS
WHERE ERROR_COUNT > 0
ORDER BY EDGE_NAME;

WITH SOURCE_ERRORS (RELATION_NAME, ERROR_COUNT) AS (
  SELECT 'SCOPE_UNKNOWN_OR_MISSING', COUNT(*)
  FROM V_KG_SOURCE_SCOPE_AUDIT
  WHERE SCOPE_STATUS = 'UNKNOWN_OR_MISSING'
  UNION ALL
  SELECT 'INCIDENT_AFFECTS_SOURCE', COUNT(*)
  FROM EXT_INCIDENTS I
  JOIN EXT_STAGES S ON S.STAGE_ID = I.LOCATION_ID
  LEFT JOIN V_KG_EQUIPMENT E
    ON E.EQUIPMENT_ID = I.RELATED_EQUIPMENT_ID
  WHERE I.RELATED_EQUIPMENT_ID IS NOT NULL
    AND E.EQUIPMENT_ID IS NULL
  UNION ALL
  SELECT 'EQUIPMENT_LOT_SOURCE', COUNT(*)
  FROM EXT_EQUIPMENT_MASTER E
  JOIN EXT_STAGES S ON S.STAGE_ID = E.STAGE_ID
  LEFT JOIN LSF_KG_LOT_PATCH P
    ON P.EQUIPMENT_ID = E.EQUIPMENT_ID
   AND P.ASSERTION_STATUS = 'SYNTHETIC'
  WHERE COALESCE(P.MANUFACTURING_LOT, E.MANUFACTURING_LOT) IS NULL
  UNION ALL
  SELECT 'EQUIPMENT_STAGE_SOURCE', COUNT(*)
  FROM EXT_EQUIPMENT_MASTER E
  LEFT JOIN V_KG_LOCATION_SCOPE S ON S.LOCATION_ID = E.STAGE_ID
  WHERE S.LOCATION_ID IS NULL
  UNION ALL
  SELECT 'INCIDENT_DOCUMENT_SOURCE', COUNT(*)
  FROM EXT_INCIDENTS I
  JOIN EXT_STAGES S ON S.STAGE_ID = I.LOCATION_ID
  LEFT JOIN EXT_DOCUMENT_CATALOG D ON D.DOCUMENT_ID = I.DOCUMENT_ID
  WHERE I.DOCUMENT_ID IS NOT NULL
    AND D.DOCUMENT_ID IS NULL
  UNION ALL
  SELECT 'INCIDENT_TASK_SOURCE', COUNT(*)
  FROM LSF_IMPROVEMENT_TASKS T
  LEFT JOIN EXT_INCIDENTS I ON I.INCIDENT_ID = T.INCIDENT_ID
  WHERE I.INCIDENT_ID IS NULL
  UNION ALL
  SELECT 'LOT_PATCH_SOURCE', COUNT(*)
  FROM LSF_KG_LOT_PATCH P
  LEFT JOIN V_KG_EQUIPMENT E ON E.EQUIPMENT_ID = P.EQUIPMENT_ID
  WHERE E.EQUIPMENT_ID IS NULL
  UNION ALL
  SELECT 'TASK_EQUIPMENT_SOURCE', COUNT(*)
  FROM LSF_KG_TASK_EQUIPMENT M
  LEFT JOIN V_KG_TASKS T ON T.TASK_ID = M.TASK_ID
  LEFT JOIN V_KG_EQUIPMENT E ON E.EQUIPMENT_ID = M.EQUIPMENT_ID
  WHERE T.TASK_ID IS NULL OR E.EQUIPMENT_ID IS NULL
  UNION ALL
  SELECT 'TASK_DOCUMENT_SOURCE', COUNT(*)
  FROM LSF_KG_TASK_DOCUMENT M
  LEFT JOIN V_KG_TASKS T ON T.TASK_ID = M.TASK_ID
  LEFT JOIN V_KG_DOCUMENTS D ON D.DOCUMENT_ID = M.DOCUMENT_ID
  WHERE T.TASK_ID IS NULL OR D.DOCUMENT_ID IS NULL
  UNION ALL
  SELECT 'LOT_DOCUMENT_SOURCE', COUNT(*)
  FROM LSF_KG_LOT_DOCUMENT M
  LEFT JOIN V_KG_LOTS L
    ON L.MANUFACTURING_LOT = M.MANUFACTURING_LOT
  LEFT JOIN V_KG_DOCUMENTS D ON D.DOCUMENT_ID = M.DOCUMENT_ID
  WHERE L.MANUFACTURING_LOT IS NULL OR D.DOCUMENT_ID IS NULL
)
SELECT RELATION_NAME, ERROR_COUNT
FROM SOURCE_ERRORS
WHERE ERROR_COUNT > 0
ORDER BY RELATION_NAME;
