-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 1798-1903; console output omitted.

CREATE OR REPLACE PROPERTY GRAPH LSF_FESTIVAL_OPS_GRAPH
  VERTEX TABLES (
    V_KG_INCIDENTS AS INCIDENTS
      KEY (INCIDENT_ID)
      LABEL INCIDENT
      PROPERTIES (
        INCIDENT_ID, FESTIVAL_DATE, LOCATION_ID, CATEGORY,
        SEVERITY, START_TS, END_TS, TITLE, STATUS, DOCUMENT_ID
      ),

    V_KG_EQUIPMENT AS EQUIPMENTS
      KEY (EQUIPMENT_ID)
      LABEL EQUIPMENT
      PROPERTIES (
        EQUIPMENT_ID, STAGE_ID, EQUIPMENT_CATEGORY, MODEL_NAME,
        SERIAL_NUMBER, MANUFACTURING_LOT, FIRMWARE_VERSION,
        CRITICALITY, LOT_SOURCE, LOT_ASSERTION_STATUS,
        LOT_SOURCE_REFERENCE_ID
      ),

    V_KG_STAGES AS STAGES
      KEY (STAGE_ID)
      LABEL STAGE
      PROPERTIES (STAGE_ID, STAGE_NAME, STAGE_TYPE, CAPACITY),

    V_KG_LOTS AS LOTS
      KEY (MANUFACTURING_LOT)
      LABEL MANUFACTURING_LOT
      PROPERTIES (MANUFACTURING_LOT),

    V_KG_TASKS AS TASKS
      KEY (TASK_ID)
      LABEL TASK
      PROPERTIES (
        TASK_ID, TASK_CODE, INCIDENT_ID, TASK_TITLE,
        PRIORITY, OWNER_TEAM_ID, CREATED_BY_AGENT, CREATED_AT, STATUS
      ),

    V_KG_DOCUMENTS AS DOCUMENTS
      KEY (DOCUMENT_ID)
      LABEL DOCUMENT
      PROPERTIES (
        DOCUMENT_ID, FILE_NAME, DOCUMENT_TYPE,
        VERSION, EFFECTIVE_DATE, PURPOSE
      )
  )
  EDGE TABLES (
    V_KG_INCIDENT_AFFECTS AS INCIDENT_AFFECTS
      KEY (EDGE_ID)
      SOURCE KEY (INCIDENT_ID) REFERENCES INCIDENTS (INCIDENT_ID)
      DESTINATION KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS (EQUIPMENT_ID)
      LABEL AFFECTS NO PROPERTIES,

    V_KG_EQUIPMENT_LOT AS EQUIPMENT_LOT
      KEY (EDGE_ID)
      SOURCE KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS (EQUIPMENT_ID)
      DESTINATION KEY (MANUFACTURING_LOT)
        REFERENCES LOTS (MANUFACTURING_LOT)
      LABEL BELONGS_TO_LOT
      PROPERTIES (
        LOT_SOURCE, LOT_ASSERTION_STATUS, LOT_SOURCE_REFERENCE_ID
      ),

    V_KG_EQUIPMENT_STAGE AS EQUIPMENT_STAGE
      KEY (EDGE_ID)
      SOURCE KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS (EQUIPMENT_ID)
      DESTINATION KEY (STAGE_ID) REFERENCES STAGES (STAGE_ID)
      LABEL DEPLOYED_AT NO PROPERTIES,

    V_KG_INCIDENT_DOCUMENT AS INCIDENT_DOCUMENT
      KEY (EDGE_ID)
      SOURCE KEY (INCIDENT_ID) REFERENCES INCIDENTS (INCIDENT_ID)
      DESTINATION KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (DOCUMENT_ID)
      LABEL DOCUMENTED_BY NO PROPERTIES,

    V_KG_INCIDENT_TASK AS INCIDENT_TASK
      KEY (EDGE_ID)
      SOURCE KEY (INCIDENT_ID) REFERENCES INCIDENTS (INCIDENT_ID)
      DESTINATION KEY (TASK_ID) REFERENCES TASKS (TASK_ID)
      LABEL CREATES NO PROPERTIES,

    V_KG_TASK_EQUIPMENT AS TASK_EQUIPMENT
      KEY (EDGE_ID)
      SOURCE KEY (TASK_ID) REFERENCES TASKS (TASK_ID)
      DESTINATION KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS (EQUIPMENT_ID)
      LABEL TARGETS
      PROPERTIES (SOURCE_TYPE, SOURCE_REFERENCE_ID),

    V_KG_TASK_DOCUMENT AS TASK_DOCUMENT
      KEY (EDGE_ID)
      SOURCE KEY (TASK_ID) REFERENCES TASKS (TASK_ID)
      DESTINATION KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (DOCUMENT_ID)
      LABEL USES_PROCEDURE
      PROPERTIES (SOURCE_TYPE, SOURCE_REFERENCE_ID),

    V_KG_LOT_DOCUMENT AS LOT_DOCUMENT
      KEY (EDGE_ID)
      SOURCE KEY (MANUFACTURING_LOT)
        REFERENCES LOTS (MANUFACTURING_LOT)
      DESTINATION KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (DOCUMENT_ID)
      LABEL GOVERNED_BY
      PROPERTIES (RELATION_TYPE, SOURCE_TYPE, SOURCE_REFERENCE_ID)
  )
  OPTIONS (TRUSTED MODE, DISALLOW MIXED PROPERTY TYPES);
