-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 2294-2312; console output omitted.

CREATE OR REPLACE PACKAGE LSF_KG_API AUTHID DEFINER AS
  PROCEDURE GET_INCIDENT_IMPACT (
    P_INCIDENT_ID IN  VARCHAR2,
    P_RESULT      OUT CLOB
  );

  PROCEDURE GET_OPEN_TASKS (
    P_INCIDENT_ID IN  VARCHAR2,
    P_RESULT      OUT CLOB
  );

  PROCEDURE GET_RELATED_DOCUMENTS (
    P_INCIDENT_ID IN  VARCHAR2,
    P_RESULT      OUT CLOB
  );
END LSF_KG_API;
/
