-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 2677-2684; console output omitted.

GRANT EXECUTE ON LSF_KG_API TO LSF_AGENT;

GRANT SELECT ON V_KG_INCIDENTS TO LSF_AGENT;
GRANT SELECT ON V_KG_EQUIPMENT TO LSF_AGENT;
GRANT SELECT ON V_KG_TASKS TO LSF_AGENT;
GRANT SELECT ON EXT_EQUIPMENT_MAINTENANCE TO LSF_AGENT;
