-- Run as LSF_AGENT.

-- Extracted from blog v1.3 lines 2747-2774; console output omitted.

CREATE OR REPLACE PROCEDURE LSF_GET_INCIDENT_IMPACT (
  P_INCIDENT_ID IN VARCHAR2,
  P_RESULT OUT CLOB
) AUTHID DEFINER AS
BEGIN
  ADB_USER.LSF_KG_API.GET_INCIDENT_IMPACT(P_INCIDENT_ID, P_RESULT);
END;
/

CREATE OR REPLACE PROCEDURE LSF_GET_OPEN_TASKS (
  P_INCIDENT_ID IN VARCHAR2,
  P_RESULT OUT CLOB
) AUTHID DEFINER AS
BEGIN
  ADB_USER.LSF_KG_API.GET_OPEN_TASKS(P_INCIDENT_ID, P_RESULT);
END;
/

CREATE OR REPLACE PROCEDURE LSF_GET_RELATED_DOCUMENTS (
  P_INCIDENT_ID IN VARCHAR2,
  P_RESULT OUT CLOB
) AUTHID DEFINER AS
BEGIN
  ADB_USER.LSF_KG_API.GET_RELATED_DOCUMENTS(P_INCIDENT_ID, P_RESULT);
END;
/
