-- Run as ADB_USER in SQLcl / SQL*Plus.
-- Requires the previous article views and the ontology V_KG_* views.
-- PAF Data Analysis Agent selects ADB_USER.V_KG_INCIDENT_FACTS only.
-- Source definitions were checked against the published article.
-- This script has not been executed against your Oracle Database here.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON

BEGIN
  IF USER <> 'ADB_USER' THEN
    RAISE_APPLICATION_ERROR(-20070, 'Connect as ADB_USER to create the facts view');
  END IF;
END;
/

CREATE OR REPLACE VIEW V_KG_INCIDENT_FACTS AS
WITH SENSOR_DAY AS (
  SELECT FESTIVAL_DATE, STAGE_ID, EQUIPMENT_ID,
         MAX(CASE WHEN METRIC_NAME = 'temperature_c'
                  THEN MAX_METRIC_VALUE END) AS DAILY_MAX_TEMPERATURE_C,
         MAX(CASE WHEN METRIC_NAME = 'packet_loss_pct'
                  THEN MAX_METRIC_VALUE END) AS DAILY_MAX_PACKET_LOSS_PCT,
         MIN(CASE WHEN METRIC_NAME = 'fan_rpm'
                  THEN MIN_METRIC_VALUE END) AS DAILY_MIN_FAN_RPM
  FROM V_EQUIPMENT_HEALTH_SUMMARY
  GROUP BY FESTIVAL_DATE, STAGE_ID, EQUIPMENT_ID
), MAINTENANCE_SUMMARY AS (
  SELECT EQUIPMENT_ID,
         COUNT(*) AS MAINTENANCE_RECORD_COUNT,
         SUM(CASE WHEN STATUS = 'OVERDUE' THEN 1 ELSE 0 END)
           AS OVERDUE_MAINTENANCE_COUNT,
         MIN(CASE WHEN STATUS = 'OVERDUE' THEN SCHEDULED_DATE END)
           AS EARLIEST_OVERDUE_SCHEDULED_DATE
  FROM EXT_EQUIPMENT_MAINTENANCE
  GROUP BY EQUIPMENT_ID
), DELAY_SUMMARY AS (
  SELECT INCIDENT_ID, COUNT(*) AS AFFECTED_PERFORMANCE_COUNT,
         MAX(DELAY_MINUTES) AS MAX_DELAY_MINUTES
  FROM V_STAGE_DELAY_ANALYSIS
  WHERE INCIDENT_ID IS NOT NULL
  GROUP BY INCIDENT_ID
)
SELECT I.INCIDENT_ID, I.FESTIVAL_DATE,
       I.LOCATION_ID AS INCIDENT_LOCATION_ID,
       I.CATEGORY AS INCIDENT_CATEGORY,
       I.SEVERITY AS INCIDENT_SEVERITY,
       I.START_TS AS INCIDENT_START_TS,
       I.END_TS AS INCIDENT_END_TS,
       I.TITLE AS INCIDENT_TITLE,
       I.STATUS AS INCIDENT_STATUS,
       I.DOCUMENT_ID AS INCIDENT_DOCUMENT_ID,
       I.RELATED_EQUIPMENT_ID AS AFFECTED_EQUIPMENT_ID,
       E.STAGE_ID AS EQUIPMENT_STAGE_ID,
       S.STAGE_NAME AS EQUIPMENT_STAGE_NAME,
       E.MANUFACTURING_LOT,
       E.LOT_SOURCE, E.LOT_ASSERTION_STATUS, E.LOT_SOURCE_REFERENCE_ID,
       H.DAILY_MAX_TEMPERATURE_C,
       H.DAILY_MAX_PACKET_LOSS_PCT,
       H.DAILY_MIN_FAN_RPM,
       M.MAINTENANCE_RECORD_COUNT,
       M.OVERDUE_MAINTENANCE_COUNT,
       M.EARLIEST_OVERDUE_SCHEDULED_DATE,
       D.AFFECTED_PERFORMANCE_COUNT,
       D.MAX_DELAY_MINUTES
FROM V_KG_INCIDENTS I
LEFT JOIN V_KG_EQUIPMENT E ON E.EQUIPMENT_ID = I.RELATED_EQUIPMENT_ID
LEFT JOIN V_KG_STAGES S ON S.STAGE_ID = E.STAGE_ID
LEFT JOIN SENSOR_DAY H
  ON H.FESTIVAL_DATE = I.FESTIVAL_DATE
 AND H.STAGE_ID = E.STAGE_ID
 AND H.EQUIPMENT_ID = E.EQUIPMENT_ID
LEFT JOIN MAINTENANCE_SUMMARY M ON M.EQUIPMENT_ID = E.EQUIPMENT_ID
LEFT JOIN DELAY_SUMMARY D ON D.INCIDENT_ID = I.INCIDENT_ID;

COMMENT ON TABLE V_KG_INCIDENT_FACTS IS
  'Incident単位の分析View。センサーはIncident当日の機材日次集計。保守は元データでOVERDUEの件数と最も早い予定日。Task・関連文書の経路はGraph APIで取得する。';
COMMENT ON COLUMN V_KG_INCIDENT_FACTS.DAILY_MAX_TEMPERATURE_C IS
  'Incident当日の機材の日次最大温度。障害発生時間帯だけの値ではない';
COMMENT ON COLUMN V_KG_INCIDENT_FACTS.DAILY_MAX_PACKET_LOSS_PCT IS
  'Incident当日の機材の日次最大パケットロス率（%）';
COMMENT ON COLUMN V_KG_INCIDENT_FACTS.DAILY_MIN_FAN_RPM IS
  'Incident当日の機材の日次最低ファン回転数（RPM）';
COMMENT ON COLUMN V_KG_INCIDENT_FACTS.EARLIEST_OVERDUE_SCHEDULED_DATE IS
  '元データのSTATUS=OVERDUEの保守予定日の最小値。Incident時点の保守状態を履歴から再構成したものではない';
COMMENT ON COLUMN V_KG_INCIDENT_FACTS.AFFECTED_PERFORMANCE_COUNT IS
  'V_STAGE_DELAY_ANALYSISでIncident IDが一致する公演行の件数';

GRANT SELECT ON V_KG_INCIDENT_FACTS TO LSF_AGENT;

-- Must return no rows: aggregating each source before joining prevents fan-out.
SELECT INCIDENT_ID, COUNT(*) AS ROW_COUNT
FROM V_KG_INCIDENT_FACTS
GROUP BY INCIDENT_ID
HAVING COUNT(*) <> 1;

-- Expected for INC-2026-081: 1 row, EQ-NET-WA-01,
-- daily sensor values 91.755 / 19.167 / 120,
-- earliest overdue scheduled date 2026-07-25,
-- affected performance count 3, maximum delay 29.
SELECT INCIDENT_ID, FESTIVAL_DATE, AFFECTED_EQUIPMENT_ID,
       DAILY_MAX_TEMPERATURE_C, DAILY_MAX_PACKET_LOSS_PCT,
       DAILY_MIN_FAN_RPM, MAINTENANCE_RECORD_COUNT,
       OVERDUE_MAINTENANCE_COUNT, EARLIEST_OVERDUE_SCHEDULED_DATE,
       AFFECTED_PERFORMANCE_COUNT, MAX_DELAY_MINUTES
FROM V_KG_INCIDENT_FACTS
WHERE INCIDENT_ID = 'INC-2026-081';

WHENEVER SQLERROR CONTINUE NONE
