-- Run as LSF_AGENT after sql/ontology/15_create_agent_wrappers.sql.
SET LONG 100000
SET LONGCHUNKSIZE 32767

SELECT OBJECT_NAME, STATUS FROM USER_OBJECTS
WHERE OBJECT_NAME IN ('LSF_GET_INCIDENT_IMPACT', 'LSF_GET_OPEN_TASKS',
                      'LSF_GET_RELATED_DOCUMENTS')
ORDER BY OBJECT_NAME;

VAR KG_RESULT CLOB
EXEC LSF_GET_INCIDENT_IMPACT('INC-2026-081', :KG_RESULT);
SELECT COUNT(*) AS IMPACT_COUNT FROM JSON_TABLE(:KG_RESULT, '$[*]' COLUMNS (X VARCHAR2(40) PATH '$.related_equipment_id'));

EXEC LSF_GET_OPEN_TASKS('INC-2026-081', :KG_RESULT);
SELECT COUNT(*) AS OPEN_TASK_COUNT FROM JSON_TABLE(:KG_RESULT, '$[*]' COLUMNS (X NUMBER PATH '$.task_id'));

EXEC LSF_GET_RELATED_DOCUMENTS('INC-2026-081', :KG_RESULT);
SELECT COUNT(*) AS DOCUMENT_PATH_COUNT,
       COUNT(DISTINCT DOCUMENT_ID) AS DISTINCT_DOCUMENT_COUNT
FROM JSON_TABLE(:KG_RESULT, '$[*]' COLUMNS
  (DOCUMENT_ID VARCHAR2(40) PATH '$.document_id'));
