-- Run as ADB_USER. Read-only checks for the existing Select AI RAG profile and vector index.
-- Extracted from blog v1.3; console output and SPOOL commands omitted.

SHOW USER
SET LONG 1000000
SET LONGCHUNKSIZE 32767
SET PAGESIZE 1000
SET LINESIZE 250

SELECT USER AS CONNECTED_SCHEMA, SYSTIMESTAMP AS CHECKED_AT
FROM DUAL;

SELECT PROFILE_NAME, STATUS
FROM USER_CLOUD_AI_PROFILES
WHERE PROFILE_NAME = 'LSF2026_RAG_PROFILE_PAF';

SELECT ATTRIBUTE_NAME, ATTRIBUTE_VALUE
FROM USER_CLOUD_AI_PROFILE_ATTRIBUTES
WHERE PROFILE_NAME = 'LSF2026_RAG_PROFILE_PAF'
  AND ATTRIBUTE_NAME IN (
    'provider', 'credential_name', 'model', 'embedding_model',
    'region', 'vector_index_name'
  )
ORDER BY ATTRIBUTE_NAME;

SELECT INDEX_NAME, STATUS
FROM USER_CLOUD_VECTOR_INDEXES
WHERE INDEX_NAME = 'LSF2026_DOC_VECTOR';

SELECT ATTRIBUTE_NAME, ATTRIBUTE_VALUE
FROM USER_CLOUD_VECTOR_INDEX_ATTRIBUTES
WHERE INDEX_NAME = 'LSF2026_DOC_VECTOR'
  AND ATTRIBUTE_NAME IN (
    'profile_name', 'pipeline_name', 'vector_table_name',
    'location', 'match_limit', 'chunk_size', 'chunk_overlap'
  )
ORDER BY ATTRIBUTE_NAME;

SELECT COUNT(*) AS CHUNK_COUNT
FROM LSF2026_DOC_VECTOR$VECTAB;

SELECT JSON_VALUE(ATTRIBUTES, '$.object_name'
                  RETURNING VARCHAR2(4000)) AS SOURCE_OBJECT,
       COUNT(*) AS CHUNK_COUNT
FROM LSF2026_DOC_VECTOR$VECTAB
GROUP BY JSON_VALUE(ATTRIBUTES, '$.object_name'
                    RETURNING VARCHAR2(4000))
ORDER BY SOURCE_OBJECT;

WITH EXPECTED_FILES (DOCUMENT_ID, FILE_NAME) AS (
  SELECT 'IR-2026-081',
         'IR-2026-081_waveform_arena_delay_report.pdf' FROM DUAL
  UNION ALL
  SELECT 'SB-NW-2603',
         'SB-NW-2603_network_switch_cooling_fan_bulletin.pdf' FROM DUAL
  UNION ALL
  SELECT 'OPS-NET-2.1',
         'LSF2026_stage_audio_network_operations_v2.1.pdf' FROM DUAL
), CHUNKS AS (
  SELECT REGEXP_SUBSTR(
           JSON_VALUE(ATTRIBUTES, '$.object_name'
                      RETURNING VARCHAR2(4000)), '[^/]+$'
         ) AS FILE_NAME,
         COUNT(*) AS CHUNK_COUNT
  FROM LSF2026_DOC_VECTOR$VECTAB
  GROUP BY REGEXP_SUBSTR(
             JSON_VALUE(ATTRIBUTES, '$.object_name'
                        RETURNING VARCHAR2(4000)), '[^/]+$'
           )
)
SELECT F.DOCUMENT_ID,
       D.VERSION AS CATALOG_VERSION,
       F.FILE_NAME,
       D.FILE_NAME AS CATALOG_FILE_NAME,
       NVL(C.CHUNK_COUNT, 0) AS CHUNK_COUNT
FROM EXPECTED_FILES F
LEFT JOIN V_KG_DOCUMENTS D ON D.DOCUMENT_ID = F.DOCUMENT_ID
LEFT JOIN CHUNKS C ON C.FILE_NAME = F.FILE_NAME
ORDER BY F.DOCUMENT_ID;
