-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 1971-1974, blog v1.3 lines 1982-2014, blog v1.3 lines 2037-2074, blog v1.3 lines 2094-2190; console output omitted.

VAR P_INCIDENT_ID VARCHAR2(30)
EXEC :P_INCIDENT_ID := 'INC-2026-081';

SELECT *
FROM GRAPH_TABLE (
  LSF_FESTIVAL_OPS_GRAPH
  MATCH
    (I IS INCIDENT)
      -[A IS AFFECTS]->
    (E1 IS EQUIPMENT)
      -[B1 IS BELONGS_TO_LOT]->
    (L IS MANUFACTURING_LOT)
      <-[B2 IS BELONGS_TO_LOT]-
    (E2 IS EQUIPMENT)
      -[D IS DEPLOYED_AT]->
    (S IS STAGE)
  WHERE I.INCIDENT_ID = :P_INCIDENT_ID
    AND E1.EQUIPMENT_ID <> E2.EQUIPMENT_ID
  COLUMNS (
    I.INCIDENT_ID       AS INCIDENT_ID,
    E1.EQUIPMENT_ID     AS AFFECTED_EQUIPMENT_ID,
    L.MANUFACTURING_LOT AS MANUFACTURING_LOT,
    E2.EQUIPMENT_ID     AS RELATED_EQUIPMENT_ID,
    S.STAGE_ID          AS RELATED_STAGE_ID,
    S.STAGE_NAME        AS RELATED_STAGE_NAME,
    B2.LOT_SOURCE       AS LOT_SOURCE,
    B2.LOT_ASSERTION_STATUS AS LOT_ASSERTION_STATUS,
    B2.LOT_SOURCE_REFERENCE_ID AS LOT_SOURCE_REFERENCE_ID,
    B1.LOT_SOURCE AS AFFECTED_LOT_SOURCE,
    B1.LOT_ASSERTION_STATUS AS AFFECTED_LOT_ASSERTION_STATUS,
    B1.LOT_SOURCE_REFERENCE_ID AS AFFECTED_LOT_SOURCE_REFERENCE_ID
  )
)
ORDER BY RELATED_STAGE_ID, RELATED_EQUIPMENT_ID;

SELECT *
FROM GRAPH_TABLE (
  LSF_FESTIVAL_OPS_GRAPH
  MATCH
    (I IS INCIDENT)
      -[C IS CREATES]->
    (T IS TASK)
      -[X IS TARGETS]->
    (E IS EQUIPMENT)
      -[D IS DEPLOYED_AT]->
    (S IS STAGE)
  WHERE I.INCIDENT_ID = 'INC-2026-081'
    AND T.STATUS IN ('OPEN', 'IN_PROGRESS')
  COLUMNS (
    I.INCIDENT_ID   AS INCIDENT_ID,
    T.TASK_ID       AS TASK_ID,
    T.TASK_CODE     AS TASK_CODE,
    T.PRIORITY      AS PRIORITY,
    T.STATUS        AS TASK_STATUS,
    E.EQUIPMENT_ID  AS EQUIPMENT_ID,
    S.STAGE_ID      AS STAGE_ID,
    S.STAGE_NAME    AS STAGE_NAME,
    T.CREATED_BY_AGENT AS CREATED_BY_AGENT,
    X.SOURCE_TYPE AS SOURCE_TYPE,
    X.SOURCE_REFERENCE_ID AS SOURCE_REFERENCE_ID
  )
)
ORDER BY
  CASE PRIORITY
    WHEN 'CRITICAL' THEN 1
    WHEN 'HIGH'     THEN 2
    WHEN 'MEDIUM'   THEN 3
    WHEN 'LOW'      THEN 4
    ELSE 5
  END,
  TASK_ID;

WITH RELATED_DOCUMENTS AS (
  SELECT *
  FROM GRAPH_TABLE (
    LSF_FESTIVAL_OPS_GRAPH
    MATCH
      (I IS INCIDENT)
        -[R IS DOCUMENTED_BY]->
      (D IS DOCUMENT)
    WHERE I.INCIDENT_ID = 'INC-2026-081'
    COLUMNS (
      D.DOCUMENT_ID AS DOCUMENT_ID,
      D.FILE_NAME AS FILE_NAME,
      D.DOCUMENT_TYPE AS DOCUMENT_TYPE,
      D.VERSION AS DOCUMENT_VERSION,
      D.EFFECTIVE_DATE AS EFFECTIVE_DATE,
      I.INCIDENT_ID AS INCIDENT_ID,
      CAST(NULL AS VARCHAR2(40)) AS EQUIPMENT_ID,
      CAST(NULL AS VARCHAR2(40)) AS MANUFACTURING_LOT,
      CAST(NULL AS NUMBER) AS TASK_ID,
      CAST(NULL AS VARCHAR2(200)) AS TASK_CREATED_BY_AGENT,
      'INCIDENT_REPORT' AS RELATION_TYPE,
      'DOCUMENTED_BY' AS PATH,
      'INCIDENT_CSV' AS SOURCE_TYPE,
      'incidents.csv#' || I.INCIDENT_ID AS SOURCE_REFERENCE_ID,
      CAST(NULL AS VARCHAR2(30)) AS LOT_SOURCE,
      CAST(NULL AS VARCHAR2(200)) AS LOT_SOURCE_REFERENCE_ID
    )
  )
  UNION ALL
  SELECT *
  FROM GRAPH_TABLE (
    LSF_FESTIVAL_OPS_GRAPH
    MATCH
      (I IS INCIDENT)
        -[A IS AFFECTS]->
      (E IS EQUIPMENT)
        -[B IS BELONGS_TO_LOT]->
      (L IS MANUFACTURING_LOT)
        -[G IS GOVERNED_BY]->
      (D IS DOCUMENT)
    WHERE I.INCIDENT_ID = 'INC-2026-081'
    COLUMNS (
      D.DOCUMENT_ID AS DOCUMENT_ID,
      D.FILE_NAME AS FILE_NAME,
      D.DOCUMENT_TYPE AS DOCUMENT_TYPE,
      D.VERSION AS DOCUMENT_VERSION,
      D.EFFECTIVE_DATE AS EFFECTIVE_DATE,
      I.INCIDENT_ID AS INCIDENT_ID,
      E.EQUIPMENT_ID AS EQUIPMENT_ID,
      L.MANUFACTURING_LOT AS MANUFACTURING_LOT,
      CAST(NULL AS NUMBER) AS TASK_ID,
      CAST(NULL AS VARCHAR2(200)) AS TASK_CREATED_BY_AGENT,
      G.RELATION_TYPE AS RELATION_TYPE,
      'AFFECTS>BELONGS_TO_LOT>GOVERNED_BY' AS PATH,
      G.SOURCE_TYPE AS SOURCE_TYPE,
      G.SOURCE_REFERENCE_ID AS SOURCE_REFERENCE_ID,
      B.LOT_SOURCE AS LOT_SOURCE,
      B.LOT_SOURCE_REFERENCE_ID AS LOT_SOURCE_REFERENCE_ID
    )
  )
  UNION ALL
  SELECT *
  FROM GRAPH_TABLE (
    LSF_FESTIVAL_OPS_GRAPH
    MATCH
      (I IS INCIDENT)
        -[C IS CREATES]->
      (T IS TASK)
        -[U IS USES_PROCEDURE]->
      (D IS DOCUMENT)
    WHERE I.INCIDENT_ID = 'INC-2026-081'
      AND T.STATUS IN ('OPEN', 'IN_PROGRESS')
    COLUMNS (
      D.DOCUMENT_ID AS DOCUMENT_ID,
      D.FILE_NAME AS FILE_NAME,
      D.DOCUMENT_TYPE AS DOCUMENT_TYPE,
      D.VERSION AS DOCUMENT_VERSION,
      D.EFFECTIVE_DATE AS EFFECTIVE_DATE,
      I.INCIDENT_ID AS INCIDENT_ID,
      CAST(NULL AS VARCHAR2(40)) AS EQUIPMENT_ID,
      CAST(NULL AS VARCHAR2(40)) AS MANUFACTURING_LOT,
      T.TASK_ID AS TASK_ID,
      T.CREATED_BY_AGENT AS TASK_CREATED_BY_AGENT,
      'TASK_PROCEDURE' AS RELATION_TYPE,
      'CREATES>USES_PROCEDURE' AS PATH,
      U.SOURCE_TYPE AS SOURCE_TYPE,
      U.SOURCE_REFERENCE_ID AS SOURCE_REFERENCE_ID,
      CAST(NULL AS VARCHAR2(30)) AS LOT_SOURCE,
      CAST(NULL AS VARCHAR2(200)) AS LOT_SOURCE_REFERENCE_ID
    )
  )
)
SELECT *
FROM RELATED_DOCUMENTS
ORDER BY DOCUMENT_ID, RELATION_TYPE, TASK_ID;
