-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 2632-2649, blog v1.3 lines 2869-2882, blog v1.3 lines 2928-2934, blog v1.3 lines 2950-2952, blog v1.3 lines 2969-2987; console output omitted.

SET SERVEROUTPUT ON
DECLARE
  L_RESULT CLOB;
  L_ROWS JSON_ARRAY_T;
BEGIN
  LSF_KG_API.GET_INCIDENT_IMPACT('INC-2026-081', L_RESULT);
  L_ROWS := JSON_ARRAY_T.PARSE(L_RESULT);
  DBMS_OUTPUT.PUT_LINE('IMPACT_COUNT=' || L_ROWS.GET_SIZE || ' (expected 2)');
  LSF_KG_API.GET_OPEN_TASKS('INC-2026-081', L_RESULT);
  L_ROWS := JSON_ARRAY_T.PARSE(L_RESULT);
  DBMS_OUTPUT.PUT_LINE('OPEN_TASK_COUNT=' || L_ROWS.GET_SIZE || ' (expected 2)');
  LSF_KG_API.GET_RELATED_DOCUMENTS('INC-2026-081', L_RESULT);
  L_ROWS := JSON_ARRAY_T.PARSE(L_RESULT);
  DBMS_OUTPUT.PUT_LINE('DOCUMENT_PATH_COUNT=' || L_ROWS.GET_SIZE || ' (expected 7)');
END;
/

SET SERVEROUTPUT ON

DECLARE
  L_RESULT CLOB;
BEGIN
  LSF_KG_API.GET_INCIDENT_IMPACT(
    P_INCIDENT_ID => 'INC-2026-081',
    P_RESULT      => L_RESULT
  );
  DBMS_OUTPUT.PUT_LINE(DBMS_LOB.SUBSTR(L_RESULT, 32767, 1));
END;
/

SET LONG 100000
SET LONGCHUNKSIZE 100000
VAR KG_TASKS CLOB
VAR KG_DOCUMENTS CLOB
EXEC LSF_KG_API.GET_OPEN_TASKS('INC-2026-081', :KG_TASKS);

EXEC LSF_KG_API.GET_RELATED_DOCUMENTS('INC-2026-081', :KG_DOCUMENTS);

SELECT DOCUMENT_ID, DOCUMENT_VERSION, EFFECTIVE_DATE,
       TASK_ID, EQUIPMENT_ID, MANUFACTURING_LOT,
       PATH_NAME, SOURCE_TYPE, SOURCE_REFERENCE_ID
FROM JSON_TABLE(
  :KG_DOCUMENTS, '$[*]' COLUMNS (
    DOCUMENT_ID VARCHAR2(40) PATH '$.document_id',
    DOCUMENT_VERSION VARCHAR2(20) PATH '$.document_version',
    EFFECTIVE_DATE VARCHAR2(10) PATH '$.effective_date',
    TASK_ID NUMBER PATH '$.task_id',
    EQUIPMENT_ID VARCHAR2(40) PATH '$.equipment_id',
    MANUFACTURING_LOT VARCHAR2(40) PATH '$.manufacturing_lot',
    PATH_NAME VARCHAR2(100) PATH '$.path',
    SOURCE_TYPE VARCHAR2(30) PATH '$.source_type',
    SOURCE_REFERENCE_ID VARCHAR2(200) PATH '$.source_reference_id'
  )
)
ORDER BY DOCUMENT_ID, PATH_NAME, TASK_ID;
