-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 3012-3118; console output omitted.

DECLARE
  L_IMPACT       CLOB;
  L_TASKS        CLOB;
  L_DOCUMENTS    CLOB;
  L_INVALID      PLS_INTEGER;
  L_GRAPH_COUNT  PLS_INTEGER;
  L_PACKAGE_COUNT PLS_INTEGER;
  L_VERTEX_COUNT PLS_INTEGER;
  L_EDGE_COUNT PLS_INTEGER;
  L_DISTINCT_DOC PLS_INTEGER;
  L_BAD_IMPACT PLS_INTEGER;
  L_DISTINCT_PEERS PLS_INTEGER;
  L_UNEXPECTED_DOC PLS_INTEGER;
  L_BAD_PATHS    PLS_INTEGER;
  L_IMPACT_JSON  JSON_ARRAY_T;
  L_TASKS_JSON   JSON_ARRAY_T;
  L_DOCS_JSON    JSON_ARRAY_T;
BEGIN
  SELECT COUNT(*)
    INTO L_INVALID
    FROM USER_OBJECTS
   WHERE OBJECT_NAME IN ('LSF_FESTIVAL_OPS_GRAPH', 'LSF_KG_API')
     AND STATUS <> 'VALID';

  IF L_INVALID > 0 THEN
    RAISE_APPLICATION_ERROR(-20031, 'Invalid graph or package object');
  END IF;

  SELECT COUNT(*)
    INTO L_GRAPH_COUNT
    FROM USER_PROPERTY_GRAPHS
   WHERE GRAPH_NAME = 'LSF_FESTIVAL_OPS_GRAPH';

  IF L_GRAPH_COUNT <> 1 THEN
    RAISE_APPLICATION_ERROR(-20032, 'Property graph was not found');
  END IF;

  SELECT COUNT(CASE WHEN ELEMENT_KIND = 'VERTEX' THEN 1 END),
         COUNT(CASE WHEN ELEMENT_KIND = 'EDGE' THEN 1 END)
    INTO L_VERTEX_COUNT, L_EDGE_COUNT
    FROM USER_PG_ELEMENTS
   WHERE GRAPH_NAME = 'LSF_FESTIVAL_OPS_GRAPH';
  IF L_VERTEX_COUNT <> 6 OR L_EDGE_COUNT <> 8 THEN
    RAISE_APPLICATION_ERROR(-20039, 'Unexpected graph element definition counts');
  END IF;

  SELECT COUNT(*) INTO L_PACKAGE_COUNT
  FROM USER_OBJECTS
  WHERE OBJECT_NAME = 'LSF_KG_API'
    AND OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY')
    AND STATUS = 'VALID';
  IF L_PACKAGE_COUNT <> 2 THEN
    RAISE_APPLICATION_ERROR(-20038, 'Valid package and body were not found');
  END IF;

  LSF_KG_API.GET_INCIDENT_IMPACT('INC-2026-081', L_IMPACT);
  LSF_KG_API.GET_OPEN_TASKS('INC-2026-081', L_TASKS);
  LSF_KG_API.GET_RELATED_DOCUMENTS('INC-2026-081', L_DOCUMENTS);

  L_IMPACT_JSON := JSON_ARRAY_T.PARSE(L_IMPACT);
  L_TASKS_JSON  := JSON_ARRAY_T.PARSE(L_TASKS);
  L_DOCS_JSON   := JSON_ARRAY_T.PARSE(L_DOCUMENTS);

  IF L_IMPACT_JSON.GET_SIZE <> 2 THEN
    RAISE_APPLICATION_ERROR(-20033, 'Unexpected impact row count');
  END IF;

  SELECT COUNT(CASE WHEN AFFECTED_EQUIPMENT_ID IS NULL
                     OR AFFECTED_EQUIPMENT_ID <> 'EQ-NET-WA-01'
                     OR MANUFACTURING_LOT IS NULL
                     OR MANUFACTURING_LOT <> 'NW-2603'
                     OR RELATED_EQUIPMENT_ID IS NULL
                     OR RELATED_EQUIPMENT_ID NOT IN
                       ('EQ-NET-OM-01', 'EQ-NET-NG-01')
                    THEN 1 END),
         COUNT(DISTINCT RELATED_EQUIPMENT_ID)
    INTO L_BAD_IMPACT, L_DISTINCT_PEERS
    FROM JSON_TABLE(L_IMPACT, '$[*]' COLUMNS (
      AFFECTED_EQUIPMENT_ID VARCHAR2(40) PATH '$.affected_equipment_id',
      MANUFACTURING_LOT VARCHAR2(40) PATH '$.manufacturing_lot',
      RELATED_EQUIPMENT_ID VARCHAR2(40) PATH '$.related_equipment_id'
    ));
  IF L_BAD_IMPACT > 0 OR L_DISTINCT_PEERS <> 2 THEN
    RAISE_APPLICATION_ERROR(-20040, 'Unexpected incident impact IDs');
  END IF;

  IF L_TASKS_JSON.GET_SIZE <> 2 THEN
    RAISE_APPLICATION_ERROR(-20034, 'Unexpected open task row count');
  END IF;

  IF L_DOCS_JSON.GET_SIZE <> 7 THEN
    RAISE_APPLICATION_ERROR(-20035, 'Unexpected document relation count');
  END IF;

  SELECT COUNT(DISTINCT DOCUMENT_ID)
    INTO L_DISTINCT_DOC
    FROM JSON_TABLE(
      L_DOCUMENTS,
      '$[*]' COLUMNS (
        DOCUMENT_ID VARCHAR2(40) PATH '$.document_id'
      )
    )
   WHERE DOCUMENT_ID IN ('IR-2026-081', 'SB-NW-2603', 'OPS-NET-2.1');

  IF L_DISTINCT_DOC <> 3 THEN
    RAISE_APPLICATION_ERROR(-20036, 'Expected document IDs were not found');
  END IF;

  SELECT COUNT(*) INTO L_UNEXPECTED_DOC
  FROM JSON_TABLE(L_DOCUMENTS, '$[*]' COLUMNS (
    DOCUMENT_ID VARCHAR2(40) PATH '$.document_id'
  ))
  WHERE DOCUMENT_ID IS NULL OR DOCUMENT_ID NOT IN
    ('IR-2026-081', 'SB-NW-2603', 'OPS-NET-2.1');
  IF L_UNEXPECTED_DOC > 0 THEN
    RAISE_APPLICATION_ERROR(-20041, 'Unexpected document ID');
  END IF;

  SELECT COUNT(*)
    INTO L_BAD_PATHS
    FROM JSON_TABLE(
      L_DOCUMENTS,
      '$[*]' COLUMNS (
        DOCUMENT_VERSION VARCHAR2(20) PATH '$.document_version',
        INCIDENT_ID VARCHAR2(40) PATH '$.incident_id',
        EQUIPMENT_ID VARCHAR2(40) PATH '$.equipment_id',
        MANUFACTURING_LOT VARCHAR2(40) PATH '$.manufacturing_lot',
        TASK_ID NUMBER PATH '$.task_id',
        PATH_NAME VARCHAR2(100) PATH '$.path',
        SOURCE_TYPE VARCHAR2(30) PATH '$.source_type',
        SOURCE_REFERENCE_ID VARCHAR2(200) PATH '$.source_reference_id'
      )
    )
   WHERE DOCUMENT_VERSION IS NULL
      OR INCIDENT_ID IS NULL OR INCIDENT_ID <> 'INC-2026-081'
      OR SOURCE_TYPE IS NULL OR SOURCE_REFERENCE_ID IS NULL
      OR PATH_NAME IS NULL
      OR (PATH_NAME = 'CREATES>USES_PROCEDURE' AND TASK_ID IS NULL)
      OR (PATH_NAME = 'AFFECTS>BELONGS_TO_LOT>GOVERNED_BY'
          AND (EQUIPMENT_ID IS NULL OR MANUFACTURING_LOT IS NULL));

  IF L_BAD_PATHS > 0 THEN
    RAISE_APPLICATION_ERROR(-20037, 'Missing document path or provenance');
  END IF;

  DBMS_OUTPUT.PUT_LINE('Knowledge Graph postconditions: PASS');
END;
/
