-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 3139-3195; console output omitted.

WITH SQL_RESULT AS (
  SELECT DISTINCT
    I.INCIDENT_ID,
    E1.EQUIPMENT_ID AS AFFECTED_EQUIPMENT_ID,
    E1.MANUFACTURING_LOT,
    E2.EQUIPMENT_ID AS RELATED_EQUIPMENT_ID,
    S.STAGE_ID
  FROM V_KG_INCIDENTS I
  JOIN V_KG_EQUIPMENT E1
    ON E1.EQUIPMENT_ID = I.RELATED_EQUIPMENT_ID
  JOIN V_KG_EQUIPMENT E2
    ON E2.MANUFACTURING_LOT = E1.MANUFACTURING_LOT
   AND E2.EQUIPMENT_ID <> E1.EQUIPMENT_ID
  JOIN V_KG_STAGES S
    ON S.STAGE_ID = E2.STAGE_ID
  WHERE I.INCIDENT_ID = 'INC-2026-081'
), GRAPH_RESULT AS (
  SELECT DISTINCT
    INCIDENT_ID,
    AFFECTED_EQUIPMENT_ID,
    MANUFACTURING_LOT,
    RELATED_EQUIPMENT_ID,
    STAGE_ID
  FROM GRAPH_TABLE (
    LSF_FESTIVAL_OPS_GRAPH
    MATCH
      (I IS INCIDENT)
        -[A IS AFFECTS]->(E1 IS EQUIPMENT)
        -[B1 IS BELONGS_TO_LOT]->(L IS MANUFACTURING_LOT)
        <-[B2 IS BELONGS_TO_LOT]-(E2 IS EQUIPMENT)
        -[D IS DEPLOYED_AT]->(S IS STAGE)
    WHERE I.INCIDENT_ID = 'INC-2026-081'
      AND E1.EQUIPMENT_ID <> E2.EQUIPMENT_ID
    COLUMNS (
      I.INCIDENT_ID AS INCIDENT_ID,
      E1.EQUIPMENT_ID AS AFFECTED_EQUIPMENT_ID,
      L.MANUFACTURING_LOT AS MANUFACTURING_LOT,
      E2.EQUIPMENT_ID AS RELATED_EQUIPMENT_ID,
      S.STAGE_ID AS STAGE_ID
    )
  )
)
SELECT 'SQL_ONLY' AS DIFFERENCE, D.*
FROM (
  SELECT * FROM SQL_RESULT
  MINUS
  SELECT * FROM GRAPH_RESULT
) D
UNION ALL
SELECT 'GRAPH_ONLY' AS DIFFERENCE, D.*
FROM (
  SELECT * FROM GRAPH_RESULT
  MINUS
  SELECT * FROM SQL_RESULT
) D;
