-- Run as ADB_USER.

-- Extracted from blog v1.3 lines 3322-3488; console output omitted.

SET SERVEROUTPUT ON
DEFINE KG_COMPLETED_STATUS = 'CLOSED'
-- CLOSED is a test-only value for a synthetic ONTOLOGY_DEMO_SEED task.
-- This block uses savepoints and rolls every change back before returning.

DECLARE
  C_INCIDENT_ID CONSTANT VARCHAR2(40) := 'INC-2026-081';
  C_COMPLETED_STATUS CONSTANT VARCHAR2(40) := '&KG_COMPLETED_STATUS';
  L_TARGET_TASK_ID NUMBER;
  L_ORIGINAL_STATUS LSF_IMPROVEMENT_TASKS.STATUS%TYPE;
  L_RESTORED_STATUS LSF_IMPROVEMENT_TASKS.STATUS%TYPE;

  PROCEDURE REQUIRE_EQ(
    P_ACTUAL NUMBER, P_EXPECTED NUMBER, P_LABEL VARCHAR2
  ) AS
  BEGIN
    IF P_ACTUAL IS NULL OR P_ACTUAL <> P_EXPECTED THEN
      RAISE_APPLICATION_ERROR(-20061,
        P_LABEL || ': expected=' || P_EXPECTED ||
        ', actual=' || NVL(TO_CHAR(P_ACTUAL), 'NULL'));
    END IF;
  END;

  PROCEDURE CHECK_STATE(
    P_LABEL VARCHAR2,
    P_TASK_COUNT NUMBER, P_PATH_COUNT NUMBER,
    P_DOC_COUNT NUMBER, P_SB_PATH_COUNT NUMBER,
    P_LOT_PATH_COUNT NUMBER, P_TASK_PATH_COUNT NUMBER,
    P_TARGET_OPEN NUMBER
  ) AS
    L_IMPACT CLOB;
    L_TASKS CLOB;
    L_DOCS CLOB;
    L_JSON JSON_ARRAY_T;
    L_DISTINCT_DOCS NUMBER;
    L_SB_PATHS NUMBER;
    L_INCIDENT_PATHS NUMBER;
    L_LOT_PATHS NUMBER;
    L_TASK_PATHS NUMBER;
    L_UNEXPECTED_DOCS NUMBER;
    L_TARGET_OPEN NUMBER;
  BEGIN
    LSF_KG_API.GET_INCIDENT_IMPACT(C_INCIDENT_ID, L_IMPACT);
    LSF_KG_API.GET_OPEN_TASKS(C_INCIDENT_ID, L_TASKS);
    LSF_KG_API.GET_RELATED_DOCUMENTS(C_INCIDENT_ID, L_DOCS);

    L_JSON := JSON_ARRAY_T.PARSE(L_IMPACT);
    REQUIRE_EQ(L_JSON.GET_SIZE, 2, P_LABEL || '/equipment');
    L_JSON := JSON_ARRAY_T.PARSE(L_TASKS);
    REQUIRE_EQ(L_JSON.GET_SIZE, P_TASK_COUNT, P_LABEL || '/tasks');
    L_JSON := JSON_ARRAY_T.PARSE(L_DOCS);
    REQUIRE_EQ(L_JSON.GET_SIZE, P_PATH_COUNT, P_LABEL || '/paths');

    SELECT COUNT(*) INTO L_TARGET_OPEN
    FROM JSON_TABLE(L_TASKS, '$[*]' COLUMNS (
      TASK_ID NUMBER PATH '$.task_id'
    ))
    WHERE TASK_ID = L_TARGET_TASK_ID;
    REQUIRE_EQ(L_TARGET_OPEN, P_TARGET_OPEN, P_LABEL || '/target task');

    SELECT COUNT(DISTINCT DOCUMENT_ID),
           COUNT(CASE WHEN DOCUMENT_ID = 'SB-NW-2603' THEN 1 END),
           COUNT(CASE WHEN PATH_NAME = 'DOCUMENTED_BY' THEN 1 END),
           COUNT(CASE WHEN PATH_NAME =
             'AFFECTS>BELONGS_TO_LOT>GOVERNED_BY' THEN 1 END),
           COUNT(CASE WHEN PATH_NAME = 'CREATES>USES_PROCEDURE'
             THEN 1 END),
           COUNT(CASE WHEN DOCUMENT_ID IS NULL OR DOCUMENT_ID NOT IN
             ('IR-2026-081', 'SB-NW-2603', 'OPS-NET-2.1') THEN 1 END)
      INTO L_DISTINCT_DOCS, L_SB_PATHS, L_INCIDENT_PATHS,
           L_LOT_PATHS, L_TASK_PATHS, L_UNEXPECTED_DOCS
      FROM JSON_TABLE(L_DOCS, '$[*]' COLUMNS (
        DOCUMENT_ID VARCHAR2(40) PATH '$.document_id',
        PATH_NAME VARCHAR2(100) PATH '$.path'
      ));

    REQUIRE_EQ(L_DISTINCT_DOCS, P_DOC_COUNT, P_LABEL || '/document IDs');
    REQUIRE_EQ(L_SB_PATHS, P_SB_PATH_COUNT, P_LABEL || '/SB paths');
    REQUIRE_EQ(L_INCIDENT_PATHS, 1, P_LABEL || '/incident paths');
    REQUIRE_EQ(L_LOT_PATHS, P_LOT_PATH_COUNT, P_LABEL || '/lot paths');
    REQUIRE_EQ(L_TASK_PATHS, P_TASK_PATH_COUNT, P_LABEL || '/task paths');
    REQUIRE_EQ(L_UNEXPECTED_DOCS, 0, P_LABEL || '/unexpected documents');
    DBMS_OUTPUT.PUT_LINE(P_LABEL || ': PASS');
  END;
BEGIN
  SAVEPOINT KG_CONDITION_TEST;

  IF C_COMPLETED_STATUS IS NULL OR
     NOT REGEXP_LIKE(C_COMPLETED_STATUS, '^[A-Z][A-Z0-9_]{0,39}$') OR
     C_COMPLETED_STATUS IN ('OPEN', 'IN_PROGRESS') THEN
    RAISE_APPLICATION_ERROR(-20062, 'Set a valid completed status for this test');
  END IF;

  -- IDは固定せず、この記事で作った合成Taskを特定する。
  SELECT TASK_ID, STATUS
    INTO L_TARGET_TASK_ID, L_ORIGINAL_STATUS
    FROM LSF_IMPROVEMENT_TASKS
   WHERE INCIDENT_ID = C_INCIDENT_ID
     AND TASK_TITLE = 'Orbit Main StageのNW-2603予防交換'
     AND CREATED_BY_AGENT = 'ONTOLOGY_DEMO_SEED';

  CHECK_STATE('BASELINE', 2, 7, 3, 3, 2, 4, 1);

  -- ケース1: 合成Taskを1件だけ完了する。
  UPDATE LSF_IMPROVEMENT_TASKS
     SET STATUS = C_COMPLETED_STATUS
   WHERE TASK_ID = L_TARGET_TASK_ID
     AND INCIDENT_ID = C_INCIDENT_ID
     AND CREATED_BY_AGENT = 'ONTOLOGY_DEMO_SEED'
     AND STATUS = L_ORIGINAL_STATUS;
  REQUIRE_EQ(SQL%ROWCOUNT, 1, 'CASE1/update rows');
  CHECK_STATE('CASE1 TASK COMPLETED', 1, 5, 3, 2, 2, 2, 0);

  ROLLBACK TO KG_CONDITION_TEST;
  SELECT STATUS INTO L_RESTORED_STATUS
  FROM LSF_IMPROVEMENT_TASKS WHERE TASK_ID = L_TARGET_TASK_ID;
  IF L_RESTORED_STATUS IS NULL OR L_RESTORED_STATUS <> L_ORIGINAL_STATUS THEN
    RAISE_APPLICATION_ERROR(-20063, 'Task status was not restored');
  END IF;
  CHECK_STATE('RESTORED AFTER CASE1', 2, 7, 3, 3, 2, 4, 1);

  -- ケース2: Lot -> Service Bulletinの合成Relationだけを削除する。
  DELETE FROM LSF_KG_LOT_DOCUMENT
   WHERE MANUFACTURING_LOT = 'NW-2603'
     AND DOCUMENT_ID = 'SB-NW-2603'
     AND SOURCE_TYPE = 'SYNTHETIC_DEMO'
     AND SOURCE_REFERENCE_ID = 'BLOG-DEMO-DOC-001';
  REQUIRE_EQ(SQL%ROWCOUNT, 1, 'CASE2/delete lot rows');
  CHECK_STATE('CASE2 LOT PATH REMOVED', 2, 6, 3, 2, 1, 4, 1);

  ROLLBACK TO KG_CONDITION_TEST;
  CHECK_STATE('RESTORED AFTER CASE2', 2, 7, 3, 3, 2, 4, 1);

  -- ケース3: Service BulletinへのLot 1件とTask 2件を削除する。
  DELETE FROM LSF_KG_LOT_DOCUMENT
   WHERE MANUFACTURING_LOT = 'NW-2603'
     AND DOCUMENT_ID = 'SB-NW-2603'
     AND SOURCE_TYPE = 'SYNTHETIC_DEMO'
     AND SOURCE_REFERENCE_ID = 'BLOG-DEMO-DOC-001';
  REQUIRE_EQ(SQL%ROWCOUNT, 1, 'CASE3/delete lot rows');

  DELETE FROM LSF_KG_TASK_DOCUMENT D
   WHERE D.DOCUMENT_ID = 'SB-NW-2603'
     AND D.SOURCE_TYPE = 'SYNTHETIC_DEMO'
     AND D.SOURCE_REFERENCE_ID = 'BLOG-DEMO-TASK-001'
     AND EXISTS (
       SELECT 1 FROM LSF_IMPROVEMENT_TASKS T
       WHERE T.TASK_ID = D.TASK_ID
         AND T.INCIDENT_ID = C_INCIDENT_ID
         AND T.CREATED_BY_AGENT = 'ONTOLOGY_DEMO_SEED'
         AND T.TASK_TITLE IN (
           'Orbit Main StageのNW-2603予防交換',
           'Neon Groove StageのNW-2603予防交換'
         )
     );
  REQUIRE_EQ(SQL%ROWCOUNT, 2, 'CASE3/delete task rows');
  CHECK_STATE('CASE3 ALL SB PATHS REMOVED', 2, 4, 2, 0, 1, 2, 1);

  ROLLBACK TO KG_CONDITION_TEST;
  CHECK_STATE('RESTORED AFTER CASE3', 2, 7, 3, 3, 2, 4, 1);
  DBMS_OUTPUT.PUT_LINE('Condition-change tests: PASS; all changes rolled back');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO KG_CONDITION_TEST;
    RAISE;
END;
/
