-- Run as ADB_USER (Graph Studio SQL Worksheet).

-- Extracted from blog v1.3 lines 5398-5426; console output omitted.

SELECT *
FROM GRAPH_TABLE (
  ADB_USER.LSF_FESTIVAL_OPS_GRAPH
  MATCH
    (I IS INCIDENT)
      -[A IS AFFECTS]->
    (E1 IS EQUIPMENT)
      -[B1 IS BELONGS_TO_LOT]->
    (L IS MANUFACTURING_LOT)
      <-[B2 IS BELONGS_TO_LOT]-
    (E2 IS EQUIPMENT)
      -[D IS DEPLOYED_AT]->
    (S IS STAGE)
  WHERE I.INCIDENT_ID = 'INC-2026-081'
    AND E1.EQUIPMENT_ID <> E2.EQUIPMENT_ID
  COLUMNS (
    VERTEX_ID(I)  AS INCIDENT_VERTEX,
    EDGE_ID(A)    AS AFFECTS_EDGE,
    VERTEX_ID(E1) AS AFFECTED_EQUIPMENT_VERTEX,
    EDGE_ID(B1)   AS AFFECTED_LOT_EDGE,
    VERTEX_ID(L)  AS LOT_VERTEX,
    EDGE_ID(B2)   AS RELATED_LOT_EDGE,
    VERTEX_ID(E2) AS RELATED_EQUIPMENT_VERTEX,
    EDGE_ID(D)    AS DEPLOYED_AT_EDGE,
    VERTEX_ID(S)  AS STAGE_VERTEX
  )
);
