-- Run as ADB_USER after the owner views exist and ADMIN has created LSF_AGENT.
-- Direct object grants are required by the runtime user and definer-rights wrappers.
GRANT SELECT ON V_STAGE_DELAY_ANALYSIS TO LSF_AGENT;
GRANT SELECT ON V_EQUIPMENT_HEALTH_SUMMARY TO LSF_AGENT;
GRANT SELECT ON V_GATE_CONGESTION_ANALYSIS TO LSF_AGENT;
GRANT SELECT ON V_MERCH_STOCKOUT_ANALYSIS TO LSF_AGENT;
GRANT SELECT ON V_REFUND_REQUEST_CONTEXT TO LSF_AGENT;
GRANT SELECT ON EXT_INCIDENTS TO LSF_AGENT;
GRANT SELECT ON EXT_WEATHER_OBSERVATIONS TO LSF_AGENT;
