-- Run as LSF_AGENT after ADMIN grants CREATE PROCEDURE directly to LSF_AGENT.
-- This base-demo action is not selected in the Ontology PAF Flow.
CREATE OR REPLACE PROCEDURE CREATE_LSF_IMPROVEMENT_TASK (
  P_INCIDENT_ID      IN VARCHAR2,
  P_TASK_TITLE       IN VARCHAR2,
  P_TASK_DESCRIPTION IN VARCHAR2,
  P_PRIORITY         IN VARCHAR2,
  P_OWNER_TEAM_ID    IN VARCHAR2,
  P_CREATED_BY_AGENT IN VARCHAR2,
  P_TASK_ID          OUT NUMBER
) AS
BEGIN
  ADB_USER.CREATE_LSF_IMPROVEMENT_TASK(
    P_INCIDENT_ID, P_TASK_TITLE, P_TASK_DESCRIPTION, P_PRIORITY,
    P_OWNER_TEAM_ID, P_CREATED_BY_AGENT, P_TASK_ID
  );
END;
/
